// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppErrorCode = "PORT_IN_USE" | "DISK_FULL" | "INDEX_BEHIND" | "INDEX_OPTION_DISABLED" | "WALLET_LOCKED" | "RPC_WARMING_UP" | "ORD_NOT_SYNCED" | "BINARY_NOT_VERIFIED" | "WALLET_NOT_ENCRYPTED";
