// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandHistoryStatus } from "./CommandHistoryStatus";

/**
 * One row of `command_history`, as read back for the Live Command
 * Monitor UI.
 */
export type CommandHistoryEntry = { id: string, environment: string, source: string, triggering_action: string, command_display: string, started_at_ms: number, status: CommandHistoryStatus, exit_code: number | null, duration_ms: number | null, output: string, background: boolean, };
