// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandSource } from "./CommandSource";

/**
 * The confirm dialog / "Learn mode" (docs/SPEC.md item 6) view of what
 * a raw console command line would do, before anything runs.
 */
export type ConsoleCommandPreview = { 
/**
 * Which half of the console this is -- `BitcoinCli` or `OrdCli`
 * only; reuses `nk_exec::CommandSource` rather than a new type
 * since it already carries exactly this distinction.
 */
source: CommandSource, 
/**
 * The exact command that will run, with any secret argument
 * (a passphrase, a private key) already redacted -- always safe
 * to show directly in the confirm dialog.
 */
display: string, read_only: boolean, 
/**
 * True when a `--dry-run` preview should be fetched and shown
 * before the real confirmation (ord commands that support it).
 */
supports_dry_run: boolean, 
/**
 * `Some(reason)` when this must be refused outright and
 * `console_run` will error rather than execute -- a fund-moving
 * bitcoin-cli command against the wallet ord uses, or an ord
 * `create`/`restore` that could print a recovery phrase.
 */
blocked_reason: string | null, };
