// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The mnemonic, returned directly in the IPC response and nowhere
 * else (docs/SPEC.md Foundation B's sensitive channel) -- a dedicated
 * type, not reused for anything that might tempt a caller into
 * logging/storing it alongside other wallet data.
 */
export type CreateWalletResult = { mnemonic: string, };
