// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiskUsage = { 
/**
 * Total size of everything under this environment's `data_root`
 * (bitcoind's data dir, ord's index once Phase 4 adds it, logs).
 */
used_by_data_bytes: number, 
/**
 * Free space on the volume containing `data_root`, or `None` if no
 * mounted disk could be matched to it.
 */
free_on_volume_bytes: number | null, };
