// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Setup wizard progress event (docs/SPEC.md item 1: "show progress")
 * emitted on `"setup-download-progress"` while `download_and_verify_*`
 * runs. `binary` is `"bitcoin_core"` or `"ord"` so one frontend listener
 * can drive both progress bars.
 */
export type DownloadProgress = { binary: string, downloaded_bytes: number, total_bytes: number | null, };
