// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chain } from "./Chain";
import type { IndexOptions } from "./IndexOptions";

export type Environment = { chain: Chain, 
/**
 * User-facing name. Defaults to the chain's default label but is
 * editable — environments have "its own... name" per Foundation A,
 * distinct from the chain itself (e.g. a user could rename their
 * regtest environment to "Dev Box").
 */
name: string, rpc_port: number, p2p_port: number, ord_port: number, 
/**
 * This environment's own data root, e.g. `<app-data-root>/regtest` —
 * always relative to the app's shared data root (portable-mode
 * friendly, Foundation A). Every environment's bitcoind/ord/wallets/
 * logs/history live under here, fully isolated from every other
 * environment.
 */
data_root: string, index_options: IndexOptions, };
