// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandId } from "./CommandId";
import type { CommandSource } from "./CommandSource";
import type { OutputStream } from "./OutputStream";

/**
 * Streamed to the Live Command Monitor (Phase 3) as a command runs.
 * Never carries sensitive-command output — see `Sensitivity`.
 */
export type ExecEvent = { "type": "Started", id: CommandId, environment: string, source: CommandSource, triggering_action: string, 
/**
 * The command and its arguments, redacted, for display —
 * exactly what "Learn mode" and "copy command" show.
 */
command_display: string, background: boolean, } | { "type": "Output", id: CommandId, stream: OutputStream, 
/**
 * Redacted, or `SENSITIVE_OUTPUT_PLACEHOLDER` for a sensitive
 * command.
 */
chunk: string, } | { "type": "Finished", id: CommandId, exit_code: number | null, duration_ms: number, };
