// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilePreview = { size_bytes: number, content_type: string, data_url: string | null, };
