// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ord's index options (docs/SPEC.md Foundation F): each one is
 * "effectively permanent" once ord has indexed with it disabled —
 * enabling it later means a full reindex, so these are surfaced (and
 * chosen) up front, not toggled casually.
 */
export type IndexOptions = { 
/**
 * Unlocks sat-level views (docs/SPEC.md Foundation F), including
 * "all inscriptions on this sat" in reinscribe mode.
 */
index_sats: boolean, 
/**
 * Unlocks rune balances (Foundation F). Missing this fails *soft*
 * in ord, not hard (VERIFY'd in Phase 0) — rune listing itself
 * still works, just without balance data.
 */
index_runes: boolean, 
/**
 * Unlocks address lookups in the explorer (Foundation F).
 */
index_addresses: boolean, };
