// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * docs/SPEC.md item 4's REINSCRIBE MODE: picking an owned inscription
 * fills in its satpoint, and `sat` is the entry point into that sat's
 * full inscription history (`sat_inscriptions` below). `sat: None`
 * means the running ord server's `--index-sats` is off (Foundation F)
 * -- absent, not a made-up value -- confirmed live (DECISIONS.md
 * Phase 6 VERIFY) that ord's own inscription-detail JSON sets `sat`
 * to `null` in exactly that case.
 */
export type InscriptionDetail = { id: string, satpoint: string, sat: number | null, number: number, };
