// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * docs/SPEC.md item 4's Inscribe studio: single inscribe's result --
 * shared by the plain-inscribe and reinscribe Tauri commands, and by
 * each entry of a batch's result (`parse_inscribe_results`).
 */
export type InscribeResult = { id: string, location: string, fee: number, };
