// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether each interpreter the script runner supports is actually
 * usable on this machine (docs/SPEC.md item 6: "Detect whether Python
 * and Node are installed... bash is unavailable on stock Windows, so
 * say so") -- a real probe (`nk_scripts::detect_interpreters`), not a
 * PATH-presence guess; see DECISIONS.md for why that distinction
 * matters (Windows' Python Store stub, the WSL `bash.exe` stub).
 */
export type InterpreterAvailability = { language: string, available: boolean, };
