// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LogWindow = { 
/**
 * Complete lines, oldest first.
 */
lines: Array<string>, 
/**
 * Byte offset in the file where `lines` starts. Pass this back as
 * `page_before`'s `end_offset` to load the window immediately
 * before this one ("load older" / scroll up).
 */
start_offset: number, 
/**
 * `true` when `start_offset` is 0 -- there is nothing older to page
 * to, so the UI can stop offering "load older".
 */
reached_start_of_file: boolean, };
