// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiskUsage } from "./DiskUsage";

export type NodeStatus = { blocks: number, headers: number, verification_progress: number, initial_block_download: boolean, peers: number, mempool_transactions: number, mempool_bytes: number, disk: DiskUsage, uptime_seconds: number, };
