// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * docs/SPEC.md item 2's ord dashboard section: "index height vs node
 * height, indexing / caught-up status, and which index options are
 * enabled." `index_sats`/`index_runes`/`index_addresses` reflect
 * ord's own report of its *active* flags (`/status`'s `*_index`
 * booleans), not just what Nodekeeper configured -- a second,
 * independent confirmation (DECISIONS.md Phase 4 VERIFY), same
 * reasoning as everywhere else this project prefers checking the real
 * running state over trusting its own configuration.
 */
export type OrdStatus = { index_height: number, node_height: number, caught_up: boolean, index_sats: boolean, index_runes: boolean, index_addresses: boolean, uptime_seconds: number, };
