// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One script offered by the script runner (docs/SPEC.md item 6).
 * Every field here is Nodekeeper's own, never read from the script
 * file's own content -- `regtest_only` in particular: "the 'regtest
 * only' restriction is enforced by the runner, not the script," since
 * a script file could be edited to lie about it.
 */
export type ScriptInfo = { id: string, name: string, description: string, 
/**
 * Matches `nk_scripts::Interpreter`'s variant names, lowercased --
 * only "python" exists today (all 3 built-ins), but the shape
 * supports node/bash scripts later without changing it.
 */
language: string, regtest_only: boolean, };
