// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SystemCheck = { os: string, arch: string, cpu_cores: number, total_memory_bytes: number, available_memory_bytes: number, 
/**
 * Free space on the disk that contains `data_dir`, or `None` if no
 * mounted disk could be matched to that path.
 */
disk_free_bytes: number | null, };
