// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppErrorCode } from "./AppErrorCode";

/**
 * Everything a Tauri command needs to send a typed, friendly-mappable
 * error across IPC (docs/SPEC.md item 8) instead of a bare string —
 * `code` lets the frontend look up its plain-language message and
 * "what to do" action; `message` is always available as the technical
 * detail behind the toggle, including for errors with no good code.
 */
export type TypedError = { code: AppErrorCode | null, message: string, };
