// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ord wallet send`'s `{"txid", "fee"}` (sats) -- `psbt`/`asset` are
 * dropped rather than exposed, since nothing in the UI uses them yet.
 */
export type WalletSendResult = { txid: string, fee: number, };
