// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * docs/SPEC.md item 3: "Inscriptions gallery: static previews... loaded
 * from the ord server" -- just enough per entry (id + postage) for the
 * gallery to render a sandboxed `<iframe src="<ord-origin>/preview/
 * <id>">` per Foundation D; DECISIONS.md Phase 5 VERIFY confirmed
 * `/preview/<id>` (not `/content/<id>`) is the right embed target.
 */
export type WalletInscriptionEntry = { id: string, postage: number, };
