// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * docs/SPEC.md item 3: "rune balances only when the runes index is
 * enabled" (Foundation F). Forwarded as opaque JSON text rather than a
 * typed amount/symbol/divisibility struct -- DECISIONS.md Phase 5
 * VERIFY found `"runes": {}"` (name -> per-rune object) appears only
 * when the running ord server's runes index is on, but couldn't
 * confirm the non-empty per-rune value shape live.
 */
export type WalletRuneBalance = { name: string, raw: string, };
