// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * docs/SPEC.md item 3: "Balance: cardinal vs inscribed sats."
 */
export type WalletBalance = { cardinal: number, ordinal: number, total: number, };
