// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * docs/SPEC.md item 3: "Transaction history." `ord wallet
 * transactions` only reports `{transaction, confirmations}` per entry
 * (DECISIONS.md Phase 5 VERIFY) -- no amount, direction, or time -- so
 * this joins each txid against bitcoind's own wallet-scoped
 * `gettransaction` for the fields a history list actually needs.
 */
export type WalletTransactionEntry = { txid: string, 
/**
 * Net effect on the wallet's balance: negative for a send,
 * positive for a receive (bitcoind's `gettransaction.amount`,
 * already netted across every output -- no manual summing of
 * `details[]` needed).
 */
amount_sats: number, 
/**
 * Bitcoin Core's `gettransaction.confirmations` can go negative
 * for a conflicted/abandoned transaction, hence `i64` not `u64`.
 */
confirmations: number, time: number, generated: boolean, };
