// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WalletRuneBalance } from "./WalletRuneBalance";

/**
 * docs/SPEC.md item 3: "Balance: cardinal vs inscribed sats."
 */
export type WalletBalance = { cardinal: number, ordinal: number, total: number, 
/**
 * `None` when ord's runes index is disabled for this environment
 * -- absent, not empty, in that case (DECISIONS.md Phase 5
 * VERIFY: the field is genuinely missing from ord's JSON, not
 * zero). `Some(vec![])` means the index is on but the wallet owns
 * no runes yet.
 */
runes: Array<WalletRuneBalance> | null, };
