//! Generates `bitcoin.conf` per environment (docs/SPEC.md setup wizard
//! item 1): `txindex=1`, `prune=0` (pruning must be disabled — ord and
//! txindex both require an unpruned node), `server=1`, RPC bound to
//! 127.0.0.1 only, cookie auth (the default when no `rpcuser`/
//! `rpcpassword` is set — never write those), `dbcache` sized to
//! available RAM, and outbound-only P2P (`listen=0`, `natpmp=0`) --
//! owner decision, Phase 10R, 2026-09-27; see the module's own doc
//! comment on `listen`/`natpmp` for the verified real defaults this
//! turns off.
//!
//! **Network-specific settings must live under a `[section]` header, not
//! at the top level** — confirmed live against real `bitcoind` 31.1, not
//! assumed: running with `-regtest` and top-level `rpcbind`/`rpcport`/
//! `port` produced a *fatal startup error* ("Config setting for -port
//! only applied on regtest network when in [regtest] section"), even
//! though the network was already selected via the `-regtest` CLI flag.
//! `Chain::conf_section_name()` has the exact section name per chain,
//! including mainnet's `[main]` (not `[mainnet]`). All four -- `[main]`,
//! `[regtest]`, `[signet]`, `[testnet4]` -- have now been started live
//! against the real `bitcoind` through this generator (regtest/mainnet
//! earlier; signet and testnet4 in Phase 10 step 2, DECISIONS.md). Until
//! then this comment called signet/testnet4 "also live-verified" when
//! only the first two had been run.
//!
//! See DECISIONS.md for the full investigation -- this would have
//! shipped as a config that fails to start every non-mainnet
//! environment if the first version (settings all at top level) hadn't
//! been tested against the real binary before committing it.

use crate::chain::Chain;

/// `bitcoind --help` (31.1): "Maximum database cache size <n> MiB
/// (minimum 4, default: 1024)".
const MIN_DBCACHE_MIB: u64 = 4;
/// A ceiling so one environment doesn't claim an unreasonable amount of
/// RAM by default even on a very large machine — adjustable later via
/// settings (docs/SPEC.md item 9: "Resource limits (dbcache, max
/// connections)").
const MAX_DBCACHE_MIB: u64 = 8192;

/// Builds the contents of `bitcoin.conf` for one environment.
///
/// `available_memory_bytes` is typically `system_check`'s
/// `available_memory_bytes`; `already_reserved_mib` is the dbcache
/// already claimed by other currently-running environments (docs/
/// SPEC.md: "accounting for other running environments") — 0 if none.
pub fn generate_bitcoin_conf(
    chain: Chain,
    rpc_port: u16,
    p2p_port: u16,
    available_memory_bytes: u64,
    already_reserved_mib: u64,
) -> String {
    let dbcache_mib = dbcache_mib_for(available_memory_bytes, already_reserved_mib);
    let section = chain.conf_section_name();
    format!(
        "# Generated by Nodekeeper. Do not edit by hand -- changes are \
         overwritten the next time this environment starts.\n\
         txindex=1\n\
         prune=0\n\
         server=1\n\
         dbcache={dbcache_mib}\n\
         listen=0\n\
         natpmp=0\n\
         \n\
         [{section}]\n\
         rpcbind=127.0.0.1\n\
         rpcallowip=127.0.0.1\n\
         rpcport={rpc_port}\n\
         port={p2p_port}\n"
    )
}

/// Reserves a quarter of whatever RAM is left after other environments'
/// reservations, clamped to Bitcoin Core's accepted range and a sane
/// ceiling. A quarter (not more) leaves headroom for the OS, ord's own
/// index cache, and any other environment running alongside this one.
fn dbcache_mib_for(available_memory_bytes: u64, already_reserved_mib: u64) -> u64 {
    let available_mib =
        (available_memory_bytes / (1024 * 1024)).saturating_sub(already_reserved_mib);
    (available_mib / 4).clamp(MIN_DBCACHE_MIB, MAX_DBCACHE_MIB)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn gib(n: u64) -> u64 {
        n * 1024 * 1024 * 1024
    }

    #[test]
    fn conf_has_every_required_line_in_the_right_place() {
        let conf = generate_bitcoin_conf(Chain::Regtest, 18443, 18444, gib(8), 0);
        // Chain-agnostic settings above the section header.
        let (top, sectioned) = conf
            .split_once("[regtest]")
            .expect("must have a [regtest] section");
        for line in ["txindex=1", "prune=0", "server=1", "listen=0", "natpmp=0"] {
            assert!(
                top.lines().any(|l| l == line),
                "missing top-level line: {line}\nconf:\n{conf}"
            );
        }
        assert!(top.contains("dbcache="));
        // Network-specific settings must be *inside* the section, not
        // above it -- this is the exact bug a real bitcoind rejected.
        for line in [
            "rpcbind=127.0.0.1",
            "rpcallowip=127.0.0.1",
            "rpcport=18443",
            "port=18444",
        ] {
            assert!(
                sectioned.lines().any(|l| l == line),
                "missing sectioned line: {line}\nconf:\n{conf}"
            );
            assert!(
                !top.contains(line),
                "{line} must not appear above the [regtest] section\nconf:\n{conf}"
            );
        }
        // Never write rpcuser/rpcpassword -- cookie auth only.
        assert!(!conf.contains("rpcuser"));
        assert!(!conf.contains("rpcpassword"));
    }

    #[test]
    fn mainnet_uses_the_main_section_not_mainnet() {
        let conf = generate_bitcoin_conf(Chain::Mainnet, 8332, 8333, gib(8), 0);
        assert!(conf.contains("[main]"));
        assert!(!conf.contains("[mainnet]"));
    }

    #[test]
    fn every_chain_gets_its_own_correctly_named_section() {
        for chain in Chain::ALL {
            let conf = generate_bitcoin_conf(chain, 1000, 1001, gib(8), 0);
            let expected = format!("[{}]", chain.conf_section_name());
            assert!(
                conf.contains(&expected),
                "{chain:?} conf missing {expected}\nconf:\n{conf}"
            );
        }
    }

    #[test]
    fn dbcache_scales_with_available_memory_within_bounds() {
        assert_eq!(dbcache_mib_for(gib(4), 0), 1024); // 4096/4
        assert_eq!(dbcache_mib_for(gib(16), 0), 4096); // 16384/4
        assert_eq!(dbcache_mib_for(gib(256), 0), MAX_DBCACHE_MIB); // clamped
        assert_eq!(dbcache_mib_for(1024 * 1024, 0), MIN_DBCACHE_MIB); // 1 MiB available -> floor
    }

    #[test]
    fn dbcache_accounts_for_other_running_environments() {
        let solo = dbcache_mib_for(gib(16), 0);
        let shared = dbcache_mib_for(gib(16), 4096); // another environment already took 4 GiB
        assert!(shared < solo);
        assert_eq!(shared, (16384u64.saturating_sub(4096)) / 4);
    }

    #[test]
    fn never_goes_below_the_minimum_even_when_memory_is_fully_reserved() {
        assert_eq!(
            dbcache_mib_for(gib(4), gib(4) / (1024 * 1024)),
            MIN_DBCACHE_MIB
        );
    }
}
