//! Generates `bitcoin.conf` per environment (docs/SPEC.md setup wizard
//! item 1): `txindex=1`, `prune=0` (pruning must be disabled — ord and
//! txindex both require an unpruned node), `server=1`, RPC bound to
//! 127.0.0.1 only, cookie auth (the default when no `rpcuser`/
//! `rpcpassword` is set — never write those), `dbcache` sized to
//! available RAM.
//!
//! `-rpcbind` alone does nothing: real `bitcoind --help` (31.1) says
//! "This option is ignored unless -rpcallowip is also passed" — verified
//! against the actual binary, not assumed, since getting this wrong
//! would either open RPC to everything (if `rpcallowip` were forgotten
//! with a wildcard) or silently fail to bind at all.

/// `bitcoind --help` (31.1): "Maximum database cache size <n> MiB
/// (minimum 4, default: 1024)".
const MIN_DBCACHE_MIB: u64 = 4;
/// A ceiling so one environment doesn't claim an unreasonable amount of
/// RAM by default even on a very large machine — adjustable later via
/// settings (docs/SPEC.md item 9: "Resource limits (dbcache, max
/// connections)").
const MAX_DBCACHE_MIB: u64 = 8192;

/// Builds the contents of `bitcoin.conf` for one environment.
///
/// `available_memory_bytes` is typically `system_check`'s
/// `available_memory_bytes`; `already_reserved_mib` is the dbcache
/// already claimed by other currently-running environments (docs/
/// SPEC.md: "accounting for other running environments") — 0 if none.
pub fn generate_bitcoin_conf(available_memory_bytes: u64, already_reserved_mib: u64) -> String {
    let dbcache_mib = dbcache_mib_for(available_memory_bytes, already_reserved_mib);
    format!(
        "# Generated by Nodekeeper. Do not edit by hand -- changes are \
         overwritten the next time this environment starts.\n\
         txindex=1\n\
         prune=0\n\
         server=1\n\
         rpcbind=127.0.0.1\n\
         rpcallowip=127.0.0.1\n\
         dbcache={dbcache_mib}\n"
    )
}

/// Reserves a quarter of whatever RAM is left after other environments'
/// reservations, clamped to Bitcoin Core's accepted range and a sane
/// ceiling. A quarter (not more) leaves headroom for the OS, ord's own
/// index cache, and any other environment running alongside this one.
fn dbcache_mib_for(available_memory_bytes: u64, already_reserved_mib: u64) -> u64 {
    let available_mib =
        (available_memory_bytes / (1024 * 1024)).saturating_sub(already_reserved_mib);
    (available_mib / 4).clamp(MIN_DBCACHE_MIB, MAX_DBCACHE_MIB)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn gib(n: u64) -> u64 {
        n * 1024 * 1024 * 1024
    }

    #[test]
    fn conf_has_every_required_line() {
        let conf = generate_bitcoin_conf(gib(8), 0);
        for line in [
            "txindex=1",
            "prune=0",
            "server=1",
            "rpcbind=127.0.0.1",
            "rpcallowip=127.0.0.1",
        ] {
            assert!(
                conf.lines().any(|l| l == line),
                "missing line: {line}\nfull conf:\n{conf}"
            );
        }
        assert!(conf.contains("dbcache="));
        // Never write rpcuser/rpcpassword -- cookie auth only.
        assert!(!conf.contains("rpcuser"));
        assert!(!conf.contains("rpcpassword"));
    }

    #[test]
    fn dbcache_scales_with_available_memory_within_bounds() {
        assert_eq!(dbcache_mib_for(gib(4), 0), 1024); // 4096/4
        assert_eq!(dbcache_mib_for(gib(16), 0), 4096); // 16384/4
        assert_eq!(dbcache_mib_for(gib(256), 0), MAX_DBCACHE_MIB); // clamped
        assert_eq!(dbcache_mib_for(1024 * 1024, 0), MIN_DBCACHE_MIB); // 1 MiB available -> floor
    }

    #[test]
    fn dbcache_accounts_for_other_running_environments() {
        let solo = dbcache_mib_for(gib(16), 0);
        let shared = dbcache_mib_for(gib(16), 4096); // another environment already took 4 GiB
        assert!(shared < solo);
        assert_eq!(shared, (16384u64.saturating_sub(4096)) / 4);
    }

    #[test]
    fn never_goes_below_the_minimum_even_when_memory_is_fully_reserved() {
        assert_eq!(
            dbcache_mib_for(gib(4), gib(4) / (1024 * 1024)),
            MIN_DBCACHE_MIB
        );
    }
}
